# Generated by Django 2.2.6 on 2019-11-15 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rating_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='reated_at',
            new_name='created_at',
        ),
    ]
